---
format: revealjs

---
# Testing Julia Code

---

## Tests.jl

- Inbuild library to write and manage tests.
- Tests should be in `./test` with a central file `./test/runtests.jl`
- Recommended to use a `./test/setup.jl` file for all `using XYZ` statements, which is "included" in `./test/runtests.jl`
- Additional packages can be added either to the `./Project.toml` [extra] section - or in a new `./test/Project.toml` environment.
- In case of the latter: Do not add the Package itself to the `./test/Project.toml`
- Tests can be run via Pkg-Manager `]test MyTestPackage`
---

## Tests Demo

---

## Coverage.jl

- Julia library to check code coverage. Installation: `pip install coverage`.
- Testing frameworks can be run via coverage to generate code coverage data while tests run.
- Code coverage information can be viewed on the terminal using: `coverage report -m`.

---

## coverage Demo

---

## Further reading

- [pytest documentation](https://docs.pytest.org/en/6.2.x/)
- [unittest documentation](https://docs.python.org/3/library/unittest.html)
