---
title: "Applications"
---

::: callout-note
Application (most likely) opens in mid-June 2023
:::

### Requirements
- one programming language on at least intermediate level [^1] (does **not** need to be Julia)
- Basics of GIT (only! - see below)

### Important Dates
- mid-June 2023 Application opens
- mid-July 2023 Invites are send out
- 31 July 2023 Time to confirm and pay (students on waiting-list are informed)

### Application Process
There is a **two-stage** application process: first you apply - then we select (to slightly titrate a common starting-skill level) - then you get invited to confirm which includes the payment-process.

### Motivation
We will ask for a short (500 chars) motivation statement. 

For example you could state why this course will be helpful to your PhD project, why this is the right time for you to learn these skills to you or why you are excited for this topic. No need to answer all (or even any) of these questions.


[^1]: While we know it is near impossible to gauge skills adequately, we still want to have some assurance on the minimal programming experience/skill level. We will ask to self-identify as **Beginner** (e.g. experience from courses, knows basic syntax), **Advanced Beginner** (did some analyses, basic plotting is no longer a problem), **Intermediate** (used it to complete a project/paper, can decode many of the error messages), **Advanced** (developed packages, can debug 90% of problems, helps others). 
