---
title: "Project Work"
---

A considerable of time will be dedicated to project work allowing you to apply the skills you have learnt during the summer school.

We encourage you to bring your own problem (e.g. something related to your own research) and try to build a small software package for that problem.

Moreover, we will provide alternative problems to be solved:

## Project: Analyzing Spatial Data

In this project, we propose to write a package that allows for the statistical analysis of spatially indexed data.

Before starting, you might look at an data example. To this end, download [TemperatureData.jld2](TemperatureData.jld2) and read this data via

``` julia

using JLD2 
@load "TemperatureData.jld2" ## potentially correct your path
```

This will give you data frames with information on weather stations in the Netherlands, summer temperature means (in $0.1^\circ\mathrm{C}$) and summer temperature maxima (in $0.1^\circ\mathrm{C}$). It is reasonable to assume that the temperature data are temporally independent. Furthermore, assuming a normal distribution at each station is quite common for this type of data.

A reasonable package could for instance contain functions to estimate means and standard deviations station-by-station, fit linear models for $\mu$ or $\log(\sigma)$ (with, e.g., geographic coordinates as covariates), or, provided that $\sigma$ is constant over space, a linear model for the data themselves (with repetitions.) \$
