---
title: Social Program
---

## Overview


| What                                                                         | When                               | Where                                                                                         |
| ---------------------------------------------------------------------------- | ---------------------------------- | --------------------------------------------------------------------------------------------- |
| Get-together                                                                 | Sunday (8th October) 7 pm           | At a café/bar called [Metzgerei](https://maps.app.goo.gl/BchdVZWqegxgtHXi8)                   |
| BBQ                                                                          | Monday (9th October)               |                                                                                               |
| Hike to [Bärenschlössle](https://maps.app.goo.gl/xKQCuboiAR9YQksC7) + dinner | Tuesday (10th October) 6:10pm      | We start at the entrance of the [SimTech building](https://maps.app.goo.gl/M8VgfDRkFiZk8wri8) |
| Get-together/Games night                                                     | Tuesday (10th October)     ~9:15 pm | At a student pub called        [Unithekle](https://maps.app.goo.gl/NHdeJvjHiEPfvRh59)         |
| Conference dinner                                                            |               Wednesday (11th October)                     |                                                                                               |
| Bowling night                                                                             |        Thursday (12th October)       7:45 pm                     |     At the [bowling centre in Möhringen](https://maps.app.goo.gl/yi4YfoqFXtz5uEhi6)                    |

## Sunday

Get-together at 7pm at a café/bar called [Metzgerei](https://maps.app.goo.gl/BchdVZWqegxgtHXi8)
	- Closest U-Bahn station(s): Schwab-/Bebelstraße (U2, U29)
	- Closest S-Bahn station(s): Schwabstraße (S1, S2, S3, S4, S5, S6, S60)

## Monday

BBQ on campus, close to the SimTech building.

## Tuesday

On Tuesday we leave at 6:15 from the [SimTech building](https://maps.app.goo.gl/M8VgfDRkFiZk8wri8) building for an easy hike (around 30-45 min.; no elevation) through the forest towards [Bärenschlössle](https://www.baerenschloessle-stuttgart.de/de). Here, we will have time for dinner and drinks together (individually payed), after which we will head back towards campus.

[Bärenschlössle :world_map:](https://maps.app.goo.gl/xKQCuboiAR9YQksC7)

Arriving on campus you can decide to either head off for the night, or you join our group to go to [Unithekle](https://www.unithekle.de/), a student pub on campus with cheap drinks and good boardgames!



## Wednesday

Conference dinner (and Bene's birthday!)

## Thursday

On Thursday we will meet slightly before 20:00 at [bowling alley Möhringen](https://www.bowling-moehringen.de/) for a friendly tournament between groups. 

[Bowling centre in Möhringen :world_map:](https://maps.app.goo.gl/yi4YfoqFXtz5uEhi6) (8pm-10pm)
	- We want to start bowling at 8pm. Please be there about 10 minutes earlier to rent bowling shoes.
	- Closest U-Bahn station(s): SSB-Zentrum (U3, U8, U12), Vaihinger Straße (U3, U5, U6, U8, U12)
	- Closest bus stop(s): Wallgraben (N1)
	- Closest S-Bahn station(s): Vaihingen (S1, S2, S3)
		- 25 min walk
		- We recommend taking the S-Bahn from University to Vaihingen and then change to U-Bahn

Beforehand you'll have time to get some food; we prepared [a map](https://www.google.com/maps/d/u/1/edit?mid=1vJQ4JtYGulsYW2M9HvyN73yKr6ESNlk&usp=sharing) with some recommendations on the way to the bowling alley, if you head there straight from campus. 
